### ISSUE TITLE
Bug in pitch controller

### ISSUE THREAD

**Issue by janismac** [ferram4/Ferram-Aerospace-Research#113]
I played around with the pitch controller and noticed that it tries to keep a certain AoA, not a certain pitch.

A look at the source code confirms this.
In the file FerramAerospaceResearch/FARGUI/FARFlightGUI/StabilityAugmentation.cs at line 198 it says

    double pitch = (info.aoA - sys.zeroPoint) * FARMathUtil.deg2rad;

I think this should be 

    double pitch = (info.pitchAngle - sys.zeroPoint) * FARMathUtil.deg2rad;

**Comment by ferram4** [comment]
Although the name is technically wrong, as with the yaw damper, this is intended behavior.  The proposed changes will result in behavior changing as the vehicle rolls, which is not how real-life pitch dampers work, nor is it intuitive in any way.
