### ISSUE TITLE
Invalid double value

### ISSUE THREAD

**Issue by khr15714n** [ferram4/Ferram-Aerospace-Research#114]
Compiling Part 'Squad/Parts/Aero/airplaneFins/sweptWing/sweptWing' throws "Invalid double value" error.

FerramAerospaceResearch.cfg,
line 234: @PART[sweptWing]:FOR[FerramAerospaceResearch]
line 247: MidChordSweep = 33/307

Don't know whether is't 33.307 or 0.10749 (33/307).
I assume it's 33.307 comparing to the other values ...

**Comment by ferram4** [comment]
Fixed in latest commit.
