### ISSUE TITLE
Where is my FAR gui?

### ISSUE THREAD

**Issue by kaytonkla** [ferram4/Ferram-Aerospace-Research#124]
plz help me. i have not idea

**Comment by ferram4** [comment]
Reporting issues requires copies of the log, reproduction steps to cause the issue, which KSP version you're using, which FAR version you're using, and whether it was installed via CKAN.  This issue will be reopened if and when those are available.

**Comment by kaytonkla** [comment]
ny ksp version is 1.0.5 i dont know my FAR versiojn cuz gui does not appear
เมื่อ 24 ม.ค. 2016 22:07 "ferram4" <notifications@github.com> เขียนว่า

**Comment by ferram4** [comment]
Without the FAR version, logs, or reproduction steps, I cannot help you.  The FAR version is stated in the name of the zip you downloaded.  [The KSP Forums have instructions on how to provide reproduction steps and logs.](http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)  You still need to tell me whether you installed via CKAN or not either.

You must follow these steps or you cannot get support.  This isn't me being mean, this is simply that you have given me absolutely nothing to work with to fix any errors that may exist.
