### ISSUE TITLE
[feature] Implement Mass-Strength tradeoff for structural parts

### ISSUE THREAD

**Issue by DracheTek** [ferram4/Ferram-Aerospace-Research#126]
I would really like to be able to tweak mass/strength of structural parts, which really helps building planes of early ages. The original mass/strength of a fuselage is somewhat equal to 5-10mm aluminum plating, which is not necessarily needed for a propeller plane.

**Comment by ferram4** [comment]
Sorry, not happening.  I have no easy way of determining how much structural mass should easily be there and it will interfere heavily with other mods; there's already some unnecessary interference with the wing mass changing.  In addition, this will result in very nasty interactions with parts in Realism Overhaul that have been rebalanced and also completely unbalance the stock game, which uses those very high masses to compensate for the small planet size and get large rockets.

If you need ultralight structural parts, Procedural Parts will provide you with parts at much lighter masses that will do the job just as well.
