### ISSUE TITLE
FAR breaks Skipper engine with cluster of Reliants

### ISSUE THREAD

**Issue by Innumite** [ferram4/Ferram-Aerospace-Research#131]
I was able to isolate a problem I found with the Skipper engine on one of my ships. Turns out FAR somehow breaks the engine.
Please try save-editing this craft into orbit and fire its engines until the fuel has run out:
[test.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/222252/test.zip)
Behavior in vanilla KSP 1.0.5: The engine barely gets warm.
Behavior in KSP 1.0.5 modded only with FAR: Heat starts building up in the Skipper after the liquid fuel boosters have been depleted. To me it seems the emptier the 2.5m tanks get the faster the heat builds.

**Comment by ferram4** [comment]
Looking at this, this appears to be FAR somehow screwing up internal conduction.  A long-term, infinite fuel test in stock showed that the Skipper also heated itself up and exploded (though after heating up and exploding the Mk1 pod).

I'll look into fixing it for the 1.1 release.

**Comment by ferram4** [comment]
This has been fixed in v0.15.6 "Jones," and the problem was FAR messing up conduction.  All good now.
