### ISSUE TITLE
NRE on high velocity suicide atmospheric burn...

### ISSUE THREAD

**Issue by Galenmacil** [ferram4/Ferram-Aerospace-Research#145]
This was shown as an NRE in game and in the log file when I destroyed two different satellite into Kerbin atmosphere at high speed (Mach >10 at 70km altitude):

_[EXC 00:22:13.409] NullReferenceException: Object reference not set to an instance of an object
    FerramAerospaceResearch.FARAeroComponents.FARAeroPartModule.ApplyForces ()
    FerramAerospaceResearch.FARAeroComponents.FARVesselAero.CalculateAndApplyVesselAeroProperties ()
    FerramAerospaceResearch.FARAeroComponents.FARVesselAero.FixedUpdate ()_

**Comment by KAmaia** [comment]
Getting similar behaviour at >70km altitudes with this spamming my log:
[EXC 16:50:30.931] NullReferenceException: Object reference not set to an instance of an object
	FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.GetVisibleMeshData (UnityEngine.Transform t, Boolean onlyMeshes)
	FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.CreateMeshListFromTransforms (System.Collections.Generic.List`1& meshTransforms)
	FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.RebuildAllMeshData ()
	FerramAerospaceResearch.FARPartGeometry.GeometryPartModule.FixedUpdate ()

Literally thousands of log writes in a few seconds.

**Comment by ferram4** [comment]
I need more information to be able to reproduce the issue.  What mods are you using, what parts on the vehicle, everything you did and the complete and full log.

**Comment by ferram4** [comment]
Closing as there has been no reproduction steps or other information.
