### ISSUE TITLE
LF rockets fliping onto side

### ISSUE THREAD

**Issue by Lynsis** [ferram4/Ferram-Aerospace-Research#151]
seems i've ran into an issue that makes far unusable for me currently, for some un-explained reason if i use a lf engine my rocket(even with fins) decides to flip out in flight though if i use a srb everythings fine. if you know of any incompatabilities heres my mod list 

`KSP: 1.1.3 (Win64) - Unity: 5.2.4f1 - OS: Windows 10  (10.0.0) 64bit
000_AT_Utils - 1.0.2
Filter Extensions - 2.6
Toolbar - 1.7.12
USI Tools - 0.7.4
Achievements - 1.9.3
B9 Animation Modules - 1.0.3
B9 Part Switch - 1.4.3
B9 Aerospace - 6.1.2
B9 Aerospace - 6.1.2
B9 Aerospace Procedural Parts - 0.40.7
CactEye 2 - 1.1.3.4
Community Resource Pack - 0.5.4
Contract Configurator - 1.19
CC-CP-SCANSat - 0.6.0.1
Contract Pack: Clever Sats - 1.3
Contract Pack: Field Research - 1.2
Contract Pack: Giving Aircraft a Purpose - 1.2.8
Contract Pack: Kerbal Academy - 1.1.4
Contract Pack: Bases and Stations - 3.4
Contract Pack: RemoteTech - 2.1.3
Contract Pack: Sounding Rockets - 1.2
Rover Missions - 0.1.6
Contract Pack: Tourism Plus - 1.5.1
Crowd Sourced Science - 3.0.2
Deadly Reentry - 7.4.7
DMagic Orbital Science - 1.3.0.2
Contract Parser - 1.0.4
Contracts Window Plus - 1.0.6.4
Progress Parser - 1.0.5
EditorExtensionsRedux - 3.2.14
Ferram Aerospace Research - 0.15.7.2
Firespitter - 7.3
Interstellar Fuel Switch - 2.1.4
RasterPropMonitor - 0.27.1
Kerbal Attachment System - 0.5.9
Kerbin Environmental Institute - 1.1.1
Kerbal Engineer Redux - 1.1.1
Kerbal Joint Reinforcement - 3.2
Kerbal Inventory System - 1.2.12
KSP-AVC Plugin - 1.1.6.1
KWRocketryRedux - 3.0.12
Infernal Robots - 2.0.5
MarkIVSystem - 2.2.1
Modular Rocket Systems - 1.12.8
ModularFlightIntegrator - 1.1.6
NearFutureConstruction - 0.6.4
NearFutureElectrical - 0.7.8
NearFuturePropulsion - 0.7.4
NearFutureSolar - 0.6.2
NearFutureSpacecraft - 0.5.1
NRAP - 1.5.1.1
Procedural Parts - 1.2.5
QuickSearch - 3.0.3
QuizTechAeroPackContinued - 1.3.3
RCS Build Aid - 0.8.1
RCS Sounds - 5.0
RealChute - 1.4.1.1
RemoteTech - 1.7.1
ResearchBodies - 1.8.1
SCANsat - 1.1.6.6
SETI-Contracts - 0.9.7.1
SETI-Greenhouse - 0.9.5.1
SETI-ProbeParts - 1.0.1.1
SETI-Rebalance - 0.9.7.2
SETI-RebalanceMaterialsGoo - 1.0.9
SETI-RemoteTechConfig - 1.0.9
SmartParts - 1.9
SmartStage - 2.9.4
TarsierSpaceTechnology - 6.4
TextureReplacer - 2.4.13
ThrottleControlledAvionics - 3.2.3
TAC Life Support - 0.12.4
TrackingStationAmbientlight - 0.3.3
Trajectories - 1.6.3
Alternate Resource Panel - 2.8.1
TweakScale - 2.2.13
USI Core - 0.2.4
Asteroid Recycling Tech - 0.8.4
USI Exploration Pack - 0.5.4
Freight Transport Tech - 0.5.4
Kolonization Core - 0.2.4
Konstruction - 0.1
Malemute Rover - 0.1.4
Sounding Rockets - 0.4.4
UKS - 0.40.4
Unmanned before Manned - 1.0.9.6
VenStockRevamp - 1.9.5
KSP Interstellar Extended - 1.9.11
Waypoint Manager - 2.5.3
[x] Science! - 5.0`

**Comment by ferram4** [comment]
This is not an issue.  This is expected behavior for unstable rockets.  Adding fins does not guarantee that rockets will be stable; body lift created by the nose can be extremely strong.  I have no idea what changes to the aerodynamics and mass distribution are created by using an SRB in place of a liquid engine and tank in this particular case, but it is a possible outcome.

Closing as there is no bug or incorrect behavior to fix.
