### ISSUE TITLE
Transonic analysis curves not usable on 1.2.1

### ISSUE THREAD

**Issue by ss8913** [ferram4/Ferram-Aerospace-Research#155]
The guide lines (should be black) are pink.  The curves (should be blue, green, or yellow, per previous version), are also  pink.  I've talked to another user (MaxRebo) who thought this was because he was using OpenGL; apparently it is not, I am using DirectX and having the same issue - this is in the KSP_Update branch.

**Comment by fredericohpandolfo** [comment]
The same issue happens on Ubuntu 16.04 too.

**Comment by airwolfpiskin** [comment]
i believe it is an issue with the color tags as they changed from [#color] to <#color>.
i might be totaly wrong but seing how the the issue seems similar it might help.
it might not be the issue but i just wanted to bring it up just in case

**Comment by DaMichel** [comment]
Seems to be an issue with an outdated shader. I don't have Unity installed currently so I could not investigate any further.
However, I just tried commenting
```//if (!FARAssets.shaderDict.TryGetValue("FARCrossSectionGraph", out lineShader))```
out to force loading of the fallback shader
```lineShader = Shader.Find("Sprites/Default");```
which displays the colors correctly!

**Comment by ferram4** [comment]
The problem with Sprites/Default, IIRC, is that it draws underneath the vessel, which makes the finer points of the curve utterly useless.  Hence the special shader.

**Comment by ferram4** [comment]
This has been fixed for the current dev build, so I'm closing it.
