### ISSUE TITLE
RealChuteLite not working on Linux

### ISSUE THREAD

**Issue by clintonmead** [ferram4/Ferram-Aerospace-Research#158]
Just downloaded KSP_update zip, copied Ferram-Aerospace-Research-KSP_update/GameData/FerramAerospaceResearch into GameData/FerramAerospaceResearch, and chutes no longer show up in staging. Tried copying GameData/FerramAerospaceResearch/RealChuteLite to GameData/RealChuteLite but that didn't help. If I install the full version of RealChute the chutes show up in staging again.

**Comment by ferram4** [comment]
This indicates a failure to install the necessary up-to-date versions of MM 1.7.5 and MFI 1.2.3, not included in those downloads.
