### ISSUE TITLE
Flying with FAR window open, will make FAR window open in SPH once you return.

### ISSUE THREAD

**Issue by Vladokapuh** [ferram4/Ferram-Aerospace-Research#168]
If i use FAR window during flight, returning to SPH will automatically open FAR window there.
I dont think this is intended.

[KSP.docx](https://github.com/ferram4/Ferram-Aerospace-Research/files/742918/KSP.docx)

**Comment by ferram4** [comment]
This should be fixed in the latest dev builds.
