### ISSUE TITLE
Unable to use FAR

### ISSUE THREAD

**Issue by Trilliante** [ferram4/Ferram-Aerospace-Research#169]
I'm trying to use FAR, but I am unable to get the GUI to appear, have the aerodynamics work, or have control surfaces (elevons and such), work.  I don't think I have any mods that are overwriting the FAR changes.

Stuff in my GameData folder: FAR version "Lanchester", FS Hangar Extender 3, Kerbal Engineer Redux, Kopernicus, MechJeb2, Modular Flight Integrator, RCS Build Aid, Real Scale Boosters, Real Solar System, RSS-Textures, SpaveY-Expanded, SpaceY-Lifters,Squad, Tweakscale, ModuleManager.2.7.5, and a bunch of other licenses. Here is a picture if it will help: http://prntscr.com/e2xdid

I've tried deleting FAR and reinstalling it, but it doesn't work.

If you need more information from me, just ask. I've tried looking around, but have been unable to find this problem in my searches. Thanks for the help!

**Comment by ferram4** [comment]
Are you running on KSP 1.2+ or KSP 1.1.3?  FAR "Lanchester" is not compatible with KSP 1.2+

**Comment by Trilliante** [comment]
That makes sense! I am using 1.2.2. Thank you for letting me know, I'll just keep watch for the next FAR release!
