### ISSUE TITLE
Uneven voxelization on stock 2m-Mk3 adapter

### ISSUE THREAD

**Issue by ferram4** [ferram4/Ferram-Aerospace-Research#172]
Part is symmetric, voxels aren't.  The way they look it appears that the right side of the voxel model is generated as if the normals are being detected backwards; check to see if the issue is due collider or mesh shenanigans.

**Comment by blowfishpro** [comment]
The collider has a bunch of flipped normals.  I guess I discovered this a while ago and didn't bother reporting to Squad

**Comment by ferram4** [comment]
Well then, the only solution is to force the use of the mesh and see if that fixes it.  If not, then I'd need to include a replacement model to fix it.

**Comment by ferram4** [comment]
Yep, using the mesh forces it.  Doesn't seem to hurt the runtime performance too much, so I'll use that as the fix until the collider can be addressed.
