### ISSUE TITLE
Are flap action groups supposed to persist between restarts?

### ISSUE THREAD

**Issue by gordonfpanam** [ferram4/Ferram-Aerospace-Research#174]
In both branches master and KSP_update, the flaps action group defaults don't appear to persist between launches of KSP. I can set them, and the setting will persist when switching between saves (for instance, switching from a career game to a sandbox game), but it won't persist on an exit and restart.

Also there's an extra action group setting in KSP_update. Its name causes an additional scroll bar to appear due to its length. "Replace with default" suggests this is in the to-do list already.

![far action group assignment](https://cloud.githubusercontent.com/assets/25485283/23327368/72d748e6-fad0-11e6-8e99-e52f1c1078f4.png)

**Comment by ferram4** [comment]
I can confirm this, data isn't being saved or loaded anymore for some reason.  It'll be fixed.

**Comment by ferram4** [comment]
This should be fixed in https://github.com/ferram4/Ferram-Aerospace-Research/commit/9a047c851cf5a011486b2c9733bee281b5b1b0de.

**Comment by gordonfpanam** [comment]
I can confirm the extra action group name is gone, and the flap action group defaults now persist between restarts. Thanks.

The flap action group defaults are not automatically applied to new control surfaces like the spoiler (brake) action group defaults are, but that's a different issue.
