### ISSUE TITLE
Adjustable Landing Gear cause excessive drag

### ISSUE THREAD

**Issue by strongest2hu** [ferram4/Ferram-Aerospace-Research#176]
The Adjustable Landing Gear being maintained at KerbalFoundries for 1.2.2 don't play well with FAR.  When ALG are placed on the bottom of a craft, the datum line for the transonic area ruling analysis gets rotated, resulting in high drag.  This sounds a lot like "0.15.6.2V Fix new landing gear interfering with main axis determination", so I don't know if I screwed something up or if it's just broken again/still.

To reproduce:
1. Install FAR
2. Install KerbalFoundries
3. Place 3 (doesn't happen with just 2 or 1 as far as I can tell) ALG on the bottom of one or more parts in the SPH, as though you were going to build an aircraft.
4. Check transonic analysis.  If it appears normal, launch and revert, then check again: it will have rotated.
Putting the gear on the bottom of a part causes the problem, while putting it on the side (horizontal) or one vanilla 15-degree tick below doesn't.  Here it is in action: http://i.imgur.com/tSb97rK.gif

This is on a clean install of KSP 1.2.2 with KF for 1.2.2 and the FAR ksp_update branch+MFI, and it is 100% reproducible for me.  After I discovered the bottom/side thing I went back to my original heavily modded game and craft that I noticed this with, put the gear on the sides, and got back all the performance I had initially expected.  I would call that the workaround expect that landing gear on the side of a craft often aren't very useful.

Is this the kind of thing you want in the issues or is other mod support not a priority?

**Comment by ferram4** [comment]
I'll look into it.  Probably the part got rotated in some change to keep it maintained.  I'll see about fixing it.

**Comment by ferram4** [comment]
I believe this has been fixed in https://github.com/ferram4/Ferram-Aerospace-Research/commit/23323b329886e3fbb1f1d26d0c5efebe015c96aa, could you try and see if that build has fixed it @strongest2hu?

**Comment by strongest2hu** [comment]
I can't reproduce it with that new build (against the old KF/ALG release or the new one).  Thanks.
