### ISSUE TITLE
"FAR returning massive atmo density spikes" with RealChute

### ISSUE THREAD

**Issue by MikeGamerGuy** [ferram4/Ferram-Aerospace-Research#179]
In conjuction with RealChute, a craft will sometimes tear itself apart when the chute fully opens.  The bug report below uses KJR/FAR (previous dev version)/RealChute, but the behavior still occurs without KJR on the current dev version of FAR and I haven't reproduced it yet.  A current maintainer of RealChute believes it's due to "FAR returning massive atmo density spikes on the way down."

Bug Report w/ reproduction/video/log and a few follow up discussion posts: http://forum.kerbalspaceprogram.com/index.php?/topic/52931-12-realchute-parachute-systems-v1412-141016/&do=findComment&comment=2998430

Starwaster's post after he reproduced mine with atmo density log: http://forum.kerbalspaceprogram.com/index.php?/topic/52931-12-realchute-parachute-systems-v1412-141016/&do=findComment&comment=3010278

**Comment by ferram4** [comment]
Looking at this, the issue appears to be due to how RealChute is making use of the data or is accessing the method.  Nothing that can be fixed on the FAR end.  Should be fixed on the RealChute end soonish though.
