### ISSUE TITLE
Dense voxels kills FPS

### ISSUE THREAD

**Issue by KSAMissionCtrl** [ferram4/Ferram-Aerospace-Research#181]
Hopefully just a minor annoyance & not the cause of a larger issue but if I have a craft voxelized like this in the editor:

![be65147a-1621-11e7-8287-308bf4bb6fe6](https://cloud.githubusercontent.com/assets/18425575/24740883/544f2522-1a71-11e7-8f35-0251c668b19b.png)

Then the frame rate tanks enormously. However if I have a larger craft voxelized the FPS are fine. I'm wondering if the max amount of voxels are trying to be drawn over such a small volume and that's taxing the game somehow.

**Comment by ferram4** [comment]
It's simply the number of voxels being rendered.  Very small, very blocky vehicles tend to fill the voxel model more and so the game tries to render more.

Unfortunately, there's no simple fix for this and considering it's fundamentally a debug feature improving performance at the risk of adding incorrect voxelization visualization isn't worthwhile.
