### ISSUE TITLE
Incorrect voxelation of TweakScale'd parts

### ISSUE THREAD

**Issue by Virindi-AC** [ferram4/Ferram-Aerospace-Research#182]
After tweaking up the scale of an engine on an aircraft, saving the craft, and reloading, the voxelization debug shows the engine as approximately twice as big as it should be. This does appear to affect drag in flight.

Screenshot: http://www.virindi.net/junk/far_tweakscale.png

Repro steps:
-Fresh install, KSP 1.2.2 win64. TweakScale 2.3.4, ModuleManager 2.7.5, ModularFlightIntegrator 1.2.4, FAR from commit f38f1f3 in KSP_update (2017/4/6).
-New game, open SPH, load aeris 4a
-Right click the left turbojet and click the right arrow to scale it to 2.5m. Check the voxel debug, it is correct.
-Save the craft as a new craft. Exit the SPH, then load the new craft again.
-Open the voxelization debug. The engine is voxelized incorrectly.

**Comment by ferram4** [comment]
This should be fixed in the latest build.
