### ISSUE TITLE
Incorrect rounding of numbers in Flight Data display in flight

### ISSUE THREAD

**Issue by Virindi-AC** [ferram4/Ferram-Aerospace-Research#183]
In the "Flight Data" display, sometimes the angle of attack number reads as ".10", when it is not actually .1. That is, the number will go from eg. 7.7, 7.8, 7.9, 7.10, 8.0, 8.1. In the tests it does smoothly run through those values so it is obvious that it is not actually "7.1" in that example.

1.2.2 Win64, FAR f38f1f36784a43a471ac583ab12ad15112de4eb7

Screenshot: http://www.virindi.net/junk/far_decimal.png

**Comment by Virindi-AC** [comment]
Hold on, my checked out code doesn't match what is showing on github. Jeez, this might be my bad.

**Comment by Virindi-AC** [comment]
Nope, this report is correct. Seems to be a problem with the stringbuilder extensions.

**Comment by Virindi-AC** [comment]
The logic of this library code to add a number to a stringbuilder is completely broken; it fails in many cases. Examples are:
7.99 to 1 decimal place -> "7.10"
-0.1 to 1 decimal place -> "0.1"
as well as numerous possible ways that rounding can be wrong due to floating point inaccuracy.

**Comment by ferram4** [comment]
Merged the PR, so this can close.
