### ISSUE TITLE
Contract Configurator + FAR incompatibility

### ISSUE THREAD

**Issue by RagingGamer** [ferram4/Ferram-Aerospace-Research#185]
(Using the dev version obvi)
One or the other causes the menus/buildings to be un-clickable. Or rather, clicking them accomplishes nothing.

On a vanilla KSP folder, with just these two mods installed, the problem occurs.

A video of exactly what's going on. (Tried GIF but was too low quality to see what was going on)
https://youtu.be/TRlAGJSuFhQ

I ran multiple tests.
Once with both
Once with FAR+MFI
Once with CC+MFI
Once with CC
Once with CC + FAR(no MFI)

Any combination that includes FAR itself and CC causes the bug.

**Comment by ferram4** [comment]
Post a copy of ksp.log after causing the issue.

**Comment by RagingGamer** [comment]
What I saw in the F12 menu.
```
Exeption: NotSupportedException: The invoked member is not supported in a dynamic module.
Launcher here (in write): False
Launcher here (in write): False
Flight State Captured
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
Saving Achievements Tree
saved
Saving FAR Data
Exeption: NotSupportedException: The invoked member is not supported in a dynamic module.
```
(This repeated every time I "enabled" the bug)

And the full log:
https://www.dropbox.com/s/l7xgavvc8yyp3hs/KSP.log?dl=0

**Comment by ferram4** [comment]
I believe that this issue can only be fixed on the Contract Configurator end.  The incompatibility is from FAR's support for Blizzy's Toolbar, but the exception is being thrown from a part of the code that no other mods throw from.  I suspect that Contract Configurator has been built against .NET 4.0, which is substantially newer than the version of .NET that KSP and its mods are set up for.  Rebuilding Contract Configurator against .NET 3.5 should be sufficient to fix the issue, but that's out of my control.
