### ISSUE TITLE
[Mod Interaction] Gravityturn displays absurdly high drag values on rockets with payload fairings

### ISSUE THREAD

**Issue by Zuthal** [ferram4/Ferram-Aerospace-Research#187]
The following mods were installed: The latest dev release of FAR, the latest version of GravityTurn Continued, the latest version of ModuleManager and the latest version of ModularFlightIntegrator.

Issue description: When launching a rocket with a payload fairing, the air drag reported by GravityTurn reaches absurdly high values (e.g. >30 m/s^2 on a rocket with a TWR<3, while still accelerating). This influences the mod's launch profile optimisation, as it uses the air drag integrated over the flight time, along with vector and gravity losses, to optimise the launch profile.

Steps to replicate: Build a rocket with a generally aerodynamic shape and a payload fairing at the top. Have GravityTurn launch it with the stats window open, and observe the air drag number.

Images: [http://imgur.com/a/FjrjH](http://imgur.com/a/FjrjH)

**Comment by ferram4** [comment]
This cannot be addressed on the FAR end.  The error is in the way that GravityTurn calculates drag, which continues to use the stock method after it has been shut off by FAR.  In order to fix this, GravityTurn would need to reach into FAR's drag numbers through the FARAPI class and make use of that.

**Comment by Zuthal** [comment]
Okay, thank you. I already also posted the same bug report on the GravityTurn github, will add that hint for fixing it to it.
