### ISSUE TITLE
Version inconsistency

### ISSUE THREAD

**Issue by blowfishpro** [ferram4/Ferram-Aerospace-Research#189]
The latest released version is `0.15.8` for KSP `1.2.2`

However, the `.version` file says it's `0.16.0` for KSP `1.2.0`

https://github.com/ferram4/Ferram-Aerospace-Research/blob/dcbc1ac13640e6e0945daa0bf43e7679678ad1fb/GameData/FerramAerospaceResearch/FAR.version

**Comment by ferram4** [comment]
Yep, well aware of that, I derped the .version.

I've updated it in the repo but I'm reluctant to rush out another build if that's the only fix.  I'm sure there's something else that needs to be fixed.

**Comment by ferram4** [comment]
Alright, with a new version on the way, this is basically fixed.
