### ISSUE TITLE
[Feature request] Simplified interpretation of Zq and some other values in the stability derivatives panel in the editor.

### ISSUE THREAD

**Issue by Rodhern** [ferram4/Ferram-Aerospace-Research#201]
As per my questions and comments on the topic at the KSP forum, I would like to suggest what in my mind is a simpler interpretation to Zq (inverted sign) and a few other related derivatives.
Within a few days I intend to pose the question/tweak/suggestion in the form of a pull request.

**Comment by ferram4** [comment]
Closed, as any discussion on this should be handled in #203
