### ISSUE TITLE
Add extra error logging for predictions: a lot of NaN

### ISSUE THREAD

**Issue by Gordon-Dry** [ferram4/Ferram-Aerospace-Research#209]
Using latest ksp_update.

I was able to build a vessel in VAB, but instead of the launchpad I got the "camera in space" issue and a lot of NaN.

Because of the log overkill I can't assure the root is at FAR...

Log:
[2017-07-01-1 KSP.log.zip](https://github.com/ferram4/Ferram-Aerospace-Research/files/1117393/2017-07-01-1.KSP.log.zip)

**Comment by Gordon-Dry** [comment]
As it seems it's not FAR, see
http://forum.kerbalspaceprogram.com/index.php?/topic/162789-nan-spam-flight-scene-no-vessel-crash/

**Comment by ferram4** [comment]
You need to be more rigorous with your creation of reproduction steps, Gordon.  You are too fast to blame FAR for issues that are apparently not caused by FAR after more strict reproduction steps.
