### ISSUE TITLE
Kerbal Foundries gear not revoxelizing when extending/retracting

### ISSUE THREAD

**Issue by Maeyanie** [ferram4/Ferram-Aerospace-Research#213]
Not sure if this applies to all KSPWheel stuff, but with the Kerbal Foundries adjustable landing gear, they don't appear to revoxelize after animating either in the editor:
![kerbal space program 2017 07 07 - 14 15 27 45](https://user-images.githubusercontent.com/206142/27972650-18d65d24-6325-11e7-9eea-939ee971fe90.png)
![kerbal space program 2017 07 07 - 14 16 23 46](https://user-images.githubusercontent.com/206142/27972654-1bfba82e-6325-11e7-81d8-f8dd324affbd.png)

Or in flight:
![kerbal space program 2017 07 07 - 13 40 02 41](https://user-images.githubusercontent.com/206142/27972687-3d52703e-6325-11e7-9bbd-152ca67f141e.png)
![kerbal space program 2017 07 07 - 13 40 14 42](https://user-images.githubusercontent.com/206142/27972696-419d555a-6325-11e7-9065-06ac69226999.png)

**Comment by kalvindukes** [comment]
Also, the "Raise/Lower landing gear" button in SPH/VAB don't recognize them as wheels, and thus don't actually affect them. Maybe correlated?

**Comment by ferram4** [comment]
I have fixed the Toggle Gear button in the Editor, but fixes to voxelization *cannot* be implemented on my end.  KSPWheels do not work through Unity animations or any other kind of default KSP animation, and so revoxelization must be triggered by KSPWheels themselves.  Given that "Toggle Gear" for KSPWheels throws, I suspect the code isn't getting far enough.

See https://github.com/shadowmage45/KSPWheel/issues/46 for more info.

**Comment by kalvindukes** [comment]
Thanks for your continued effort!
You Rock! <3
