### ISSUE TITLE
Aerodynamic tolerances overrides

### ISSUE THREAD

**Issue by raidernick** [ferram4/Ferram-Aerospace-Research#214]
@ferram4 making this issue to remind you to look into creating overrides for parts that need higher aerodynamic tolerances like the jupiter atmospheric probe I mentioned.

**Comment by ferram4** [comment]
This should be possible in https://github.com/ferram4/Ferram-Aerospace-Research/commit/91724c390bc03759fc69ce63e6524af4a1bda2a9

Add a ModuleManager block for that code like so:
```
@PART[*]:HAS[@MODULE[FARAeroPartModule]]:AFTER[FerramAerospaceResearch]
{
	@MODULE[FARAeroPartModule]
	{
		FARPartStressTemplate
		{
		//Stress values are based on projected area, measured in kPa; Y is based on cross-sectional, while XZ is based on the projected side area
			YmaxStress = 500
			XZmaxStress = 100
		}
	}
}
```

It is important that `AFTER[FerramAerospaceResearch]` be used to ensure that all parts have FARAeroPartModules applied.  Increase the numbers above as needed; if the joint fails while oriented exactly into the flow, increase YmaxStress.  If it is wobbling or going sideways when it shouldn't fail, increase XZmasStress.
