### ISSUE TITLE
A way to make certain parts invisible to FAR

### ISSUE THREAD

**Issue by DoctorDavinci** [ferram4/Ferram-Aerospace-Research#217]
I released a mod called DCK and it has transparent/invisible aircraft armor that works amazing with the stock aero system and I was hoping that there would be a way to make the armor panels invisible to FAR's aero calculations so as to make DCK compatible with FAR

https://forum.kerbalspaceprogram.com/index.php?/topic/159310-13x-dck-v011-armor-stealth-camo-and-other-goodies-for-ksp-stock-bdac-bdmk22-sm_afvs08252017/

**Comment by ferram4** [comment]
Use a module manager patch to add the necessary model transforms and PartModule names to the FARPartModuleTransformExceptions block.  You can find examples in FARPartModuleTransformExceptions.cfg.

**Comment by DoctorDavinci** [comment]
So I have a working entry that consists of 3 or 4 lines that covers all 35 armor plates in DCK

Thing is I have no idea how to write, nor can I find any information on, an MM config that edits a non-part config file ... any assistance you can provide would be greatly appreciated

**Comment by DoctorDavinci** [comment]
I have a solution .... 

Thanks for everything - This mod, amazing discussions and my greater understanding of aerodynamics let alone KSP modding

Cheers ☺
