### ISSUE TITLE
Installing FAR replaces parachute tooltips with 'realchute' info, all display zero

### ISSUE THREAD

**Issue by medicdude** [ferram4/Ferram-Aerospace-Research#221]
I'm using CKAN to manage mods, with no other mods installed, when I install FAR (with flightintegrator and modmanager), it replaces all the parachute tooltips with 'Real Chute' and everything is listed as zero.
![far realchute issue](https://user-images.githubusercontent.com/1979662/32463328-7ffae9b2-c30a-11e7-97dd-47173a84447c.jpg)

**Comment by ferram4** [comment]
This was a GUI error, fixing in https://github.com/ferram4/Ferram-Aerospace-Research/commit/e905aa93992a020e02b18df9f68c4b94235b97c8.

However this also uncovered a bug where RealChuteLite was not calcing drag properties from the parachute drag cubes, so thanks for pointing me to that.
