### ISSUE TITLE
Dx11  FAR and SVT

### ISSUE THREAD

**Issue by agustincaniglia** [ferram4/Ferram-Aerospace-Research#222]
forcing ksp tu run on dx11 (something that I really want in order for the new mod TexturesUnlimited to work properly) messes the SVT textures. BUT, not without Ferram's FAR installed! If Far is not installed then DX11 and SVT work fine. It's just that FAR messes up something and that's when SVT textures fail to work properly. Here is an image of what breaks when it does: https://www.dropbox.com/s/gjlgdj5q8kqx9lh/KSP.bmp?dl=0
I posted this on SVT as well.

EDIT: ModularFlightIntegrator I think is what's causing the problem, this installed without FAR is enough for the texture glitches

My LOG with only Kopernicus, SVT, modularFlightIntegrator and ModuleManager2.8.1 (forcingDX11)
https://www.dropbox.com/s/t3h8pmwg4fvvz3x/KSP.log?dl=0

**Comment by ferram4** [comment]
If the issue can be reproduced without requiring a FAR installation, then that implies there is nothing to be done to fix it in FAR itself.  With that in mind, I'm closing this particular issue so that discussion is focused on the issues in more relevant places.
