### ISSUE TITLE
Overuse of splines and other performance considerations

### ISSUE THREAD

**Issue by eggrobin** [ferram4/Ferram-Aerospace-Research#3]
Echoes from IRC: [`LiftSlope`](https://github.com/ferram4/Ferram-Aerospace-Research/blob/23305810404440af3f9d925a3da6cf924da4bafd/FerramAerospaceResearch/FARAeroUtil.cs#L129) is just a division and a square root, it's not worth making that into a spline.
While previous tests by ferram4 seemed to suggest that the use of splines was significant for functions such as [`PrandtlMeyerMach`](https://github.com/ferram4/Ferram-Aerospace-Research/blob/23305810404440af3f9d925a3da6cf924da4bafd/FerramAerospaceResearch/FARAeroUtil.cs#L151), the most time-consuming bit in there is a couple of arctangents. The x86 instruction set has `FPATAN`, which is [about as slow as a trig function (~100 cycles)](http://www.agner.org/optimize/instruction_tables.pdf), so that could still be fast enough not to warrant loading a spline from memory.

[It appears](http://forum.unity3d.com/threads/194938-Benchmarking-Mathf-with-System-Math-%28big-performance-differences%29) Unity's `Mathf` _should be disposed of_ if performance is an issue. I would further suggest that _all_ intermediate calculations be done in `double`: since this will be run using x86 rather than x86-64 all floating-point operations will go to the x87 instruction set, so using float requires constantly casting back and forth between `double` and `float`.

In any case, some profiling is in order.
If splines are indeed needed, they should _not_ be uniformly sampled (and if we can use only static splines it's easier to optimise the error in _Mathematica_ than to try to do so at runtime).

**Comment by ferram4** [comment]
This is very old, and I believe at this point nearly all splines have been replaced.

**Comment by Ruedii** [comment]
If I recall any splines are computed once then approximated into more
efficiant formats.  Perhaps a bug should be opened to add this feature as a
built in math tool.
