### ISSUE TITLE
FAR creates new buttons every time I go to the space center view

### ISSUE THREAD

**Issue by meew0** [ferram4/Ferram-Aerospace-Research#41]
![Lots of buttons](https://i.imgur.com/km85XlS.png)

FAR creates more and more buttons every time I go to the space center view, as the title says. This doesn't happen with any other mod (KIDS works fine, for example).

I'm using FAR 0.14.5 on Ubuntu 14.10 (64 bit KSP). Sorry if this is a known bug in either KSP or FAR, I didn't find anything about this.

**Comment by ferram4** [comment]
Haven't been able to reproduce this recently, so I'm going to assume the bug has been squashed.
