### ISSUE TITLE
Surface-attached parts have FARBasicDragModel with incorrectly defined orientation.

### ISSUE THREAD

**Issue by allista** [ferram4/Ferram-Aerospace-Research#45]
While developing an air-breathing engine I ran into a problem with FAR:
The engine is surface-attached by a pylon and has no stack nodes. Its local axes are oriented as follows:
![Engine axes orientation](http://i.imgur.com/RQLKCvJ.png)
But being attached in default orientation to a plane in SPH it gets the maximum drag coefficient (as indicated by CdCurve in drag model debug printout). And rotating it so that its Z axis is collinear with the surface velocity gives the smallest Cd:
[Drag in the default orientation](http://i.imgur.com/59vXcgN.png)
[Drag with Z axis collinear with the surface velocity](http://i.imgur.com/LDb9gge.png)

I tested the issue with several other surface-attached parts with the same result.

**Comment by allista** [comment]
I've tested FAR v0.14.5.1 and v0.14.6 with the same result.

**Comment by ferram4** [comment]
Try using the dev build.  Since it has a built-in intake, FAR should use that for orientation data.  Make sure you use the dev build's FerramAerospaceResearch.cfg, since intake handling is going back into code to avoid some stupid situations.

**Comment by allista** [comment]
**My fault. And shame on me!**

The dev build didn't help, so I when on to read FAR code and ModuleResourceIntake disassembly to understand better how a part's orientation is inferred. And, as you may guess, I've found that my intake transform orientation was wrong. Correcting it fixed the issue both in 0.14.6 and in dev build. The beauty of it is that an intake transform directed _perpendicular_ to velocity still takes in enough air to support engines, so I couldn't see the problem.

Sorry for not testing enough before posting here.

**Comment by ferram4** [comment]
*snrk*

Please, make issues like this again.  It was quite worth the laugh. :P
