### ISSUE TITLE
Flight assistance is not disabled when not in atmosphere

### ISSUE THREAD

**Issue by vtdmhd** [ferram4/Ferram-Aerospace-Research#50]
maintaining AOA in space is somewhat funny.

**Comment by rmc3** [comment]
Can confirm, this resulted in crashing into the Mun twice before I realized FAR flight assistance was still on :) Seems to switch on when entering a suborbital trajectory.

**Comment by blowfishpro** [comment]
I believe I figured out how to fix this.  Fix is in Pull Request #55

**Comment by ferram4** [comment]
This is really old, so closing in cleanup.
