### ISSUE TITLE
Parts still shielded after cargo bay or fairing destroyed (possibly Deadly Reentry related)

### ISSUE THREAD

**Issue by MrNukealizer** [ferram4/Ferram-Aerospace-Research#52]
I'm not sure if this is a problem with FAR not updating the shielded status or DRE not doing something when parts burn up. I've already posted this issue for DRE, but I just realized it might be FAR. If it's not feel free to just close the issue.

What happens is when parts are in a cargo bay or Procedural Fairing and the bay or fairing burns up during reentry, the parts never get unshielded. I can reliably make everything else burn up our break off, then the shielded parts are immune to heat and have no drag. I've managed to have parts get a stable Kerbin orbit at 6000 meters because of the lack of drag.

**Comment by ferram4** [comment]
This is fixed with the voxel aero update.
