### ISSUE TITLE
No Aileron Control

### ISSUE THREAD

**Issue by whyyoulookinatmaname** [ferram4/Ferram-Aerospace-Research#56]
All control surfaces become completely non-functional upon installation

**Comment by whyyoulookinatmaname** [comment]
nevermind, apparently the mod doesnt work on 64-bit windows. way to screw me there

**Comment by ferram4** [comment]
Yes, win64 support is disabled for this mod; this is stated in both the forum thread that links here and on KerbalStuff.

Given that Squad has pulled win64 KSP builds from Steam and will not be providing win64 builds for 1.0, I see no reason to start supporting it now, though future versions may remove the disabling code once it is unnecessary.
