### ISSUE TITLE
Cl, Cd and Cy values for strut fragment debris are NaN

### ISSUE THREAD

**Issue by mjn33** [ferram4/Ferram-Aerospace-Research#61]
**Operating System:** Fedora 21 (Linux) x86-64

Using FAR from the voxelAeroPort branch, commit d4e5d88af2fe9a2885f745091cf3cb871c8e2f70.
Mods installed:
* ModularFlightIntegrator v1.0.0

**Reproduction steps:**
 1. Go to the SPH
 2. Load "FAR Firehound" from FAR v0.14.7 (it's got [struts](https://dl.dropboxusercontent.com/u/15422248/farbug2/screenshot13.png))
 3. Launch & takeoff
 4. Take to high speed and cause aerodynamic failure
 5. Try and find one of the strut fragments

**Expected result:**
The strut fragment is slowing down due to drag.

**Actual result:**
The strut fragment appears to have no aerodynamic properties, opening up the FAR FlightData GUI shows NaN for Cl, Cd and Cy values. This issue isn't that serious, it is a bit odd though.

[screenshot1.png](https://dl.dropboxusercontent.com/u/15422248/farbug2/screenshot1.png) (shortly after takeoff)
[screenshot5.png](https://dl.dropboxusercontent.com/u/15422248/farbug2/screenshot5.png) (going fast)
[screenshot6.png](https://dl.dropboxusercontent.com/u/15422248/farbug2/screenshot6.png) (aerodynamic failure)
[screenshot7.png](https://dl.dropboxusercontent.com/u/15422248/farbug2/screenshot7.png) (found a strut fragment)
[screenshot10.png](https://dl.dropboxusercontent.com/u/15422248/farbug2/screenshot10.png) (strut fragment still moving fast)
[screenshot12.png](https://dl.dropboxusercontent.com/u/15422248/farbug2/screenshot12.png) (still moving fast)

Contents of Player.log here: https://dl.dropboxusercontent.com/u/15422248/farbug2/Player.log

**Comment by ferram4** [comment]
Should be fixed in the latest build; make sure to get the latest configs as well, they have been updated.
