### ISSUE TITLE
Unconnected struts are treated as if extended

### ISSUE THREAD

**Issue by Gamrix** [ferram4/Ferram-Aerospace-Research#62]
nuFAR's voxel debug shows struts that have been disconnected (due to removal or movement of the part they were connected to) as if they were still extended.
![capture](https://cloud.githubusercontent.com/assets/7299303/7509574/3001fa3e-f447-11e4-81fc-9cc27b6f64e4.PNG)

As you can see, the bottom right has a strut that is not connected. It used to be connected to the satalite that was above the command pod. Disconnecting the strut resolved this issue.

I was using stock struts and this issue is reproducible.

Using FAR downloaded under an hour ago (11 PM PST) from VoxelAreoPort

**Comment by ferram4** [comment]
Oh, I think I see what's happening.  There's an "isAttached" property for each strut and I guess it's not being set properly.  Alright, this can be fixed.

**Comment by ferram4** [comment]
And the latest commit has this fixed.
