### ISSUE TITLE
v0.15 "Cannot deploy while stowed" when attempting to deploy satellites that were packed in a fairing.

### ISSUE THREAD

**Issue by hyperbolist** [ferram4/Ferram-Aerospace-Research#67]
When deploying four communications satellites according to the [standard procedure](http://remotetechnologiesgroup.github.io/RemoteTech/tutorials/keo/) I got "Cannot deploy while stowed" when trying to activate anything on the satellites after the fairing has been deployed.  It would make sense if they were actually still in the fairing, but they're completely free.  They're strutted to the inside of the fairing, so I don't believe they've being knocked around in there.

Sometimes an odd antenna here or a solar panel there or miraculously the engine of the first sat will activate.  It's inconsistent, but mostly failing over five launches.

Uninstalling FAR allowed me to deploy the satellites using the same craft on the first try.

**Comment by taraniselsu** [comment]
Sounds like a stock bug so probably not FAR. If it happens again, try to quicksave/quickload or exit the flight scene and return.

**Comment by ferram4** [comment]
Post a copy of your output log.

**Comment by ferram4** [comment]
Alright, so I've managed to reproduce this.  Seems somehow related to which part is the root part on the vessel, which is changing which parts are considered "exposed" in the voxel.  Not sure why yet though.

**Comment by ferram4** [comment]
Okay, I see what happened: I wasn't transforming the overall mesh bounds for voxelization when handling parts dropped from another vessel, whether as debris or something else.  End result was that a lot of stuff didn't get voxelized right.  Should be fixed in the current source.

**Comment by hyperbolist** [comment]
I'm sorry I was away all day and couldn't provide the output log, but thank you for looking into it and I'm glad it was easy to spot and fix.
