### ISSUE TITLE
Models who's renderer has been disabled are included as part of the mesh geometry 

### ISSUE THREAD

**Issue by MaxwellLane** [ferram4/Ferram-Aerospace-Research#68]
If a mod enabled and disables a model's renderer for effect purposes, such as Roverdude's warp drives and the drives warp bubble, the model is always included as part of the mesh geometry. This then screws up the resulting aero for what one would assume would be an aerodynamic rocket.
Here are a few images showing what I mean
Cross Section with bubble guide
![screenshot5](https://cloud.githubusercontent.com/assets/10090372/7556120/51499470-f719-11e4-84ea-34c7f9d47a27.png)
Voxel Debug with bubble guide
![screenshot4](https://cloud.githubusercontent.com/assets/10090372/7556121/607af402-f719-11e4-9aa3-5c1ed2eec0f2.png)
Cross Section without bubble guide 
![screenshot6](https://cloud.githubusercontent.com/assets/10090372/7556130/915ef23a-f719-11e4-97a5-f9a9cc31b497.png)
Voxel Debug without bubble guide
![screenshot7](https://cloud.githubusercontent.com/assets/10090372/7556131/992ba148-f719-11e4-8d6e-426eb36b0399.png)

**Comment by ferram4** [comment]
There are some plans for an easier-to-hook-into method to handle this sort of thing.  Until then, this shouldn't be an issue for this particular case in flight, at least, given that the mesh will *not* be visible initially.

**Comment by ferram4** [comment]
Mesh transforms that are disabled aren't used for voxelization anymore; this actually was fixed awhile ago, but I forgot the close this issue.  In any case, it's resolved, so closing.
