### ISSUE TITLE
Erratic fluttering of control surfaces set to follow AoA when standing still

### ISSUE THREAD

**Issue by BigNose** [ferram4/Ferram-Aerospace-Research#69]
First of all: Great work on the Euler update/remake of FAR ferram4! 

Now to my suggestion:
Control surfaces which are set to follow AoA are fluttering erratically when the craft is not moving. This is not really a problem, but looks really bad.

An easy fix would propably be to disable AoA control under a speed of a few (like 1-5) m/s.

More of a visual enhancement than a bug, but hey, it's something which bothered me a bit.

**Comment by ferram4** [comment]
I agree, this looks stupid.

Fixed it for AoA and made the Flight Systems stability augmentation cut out below 5 m/s.
