### ISSUE TITLE
FARAPI CalculateVesselAeroForces call causing aerodynamic failures

### ISSUE THREAD

**Issue by sawyerap** [ferram4/Ferram-Aerospace-Research#70]
Calling CalculateVesselAeroForces from the FARAPI appears to result in aerodynamic failures and exploding parts when trying to predict forces for a parked test vessel.

I was trying to predict forces for use in another mod, and found fins getting ripped off stationary vessels on the pad when requesting forces given a large velocity vector.

Don't rule out user error, but I do have a theory from tracing the code:

CalculateVesselAeroForces 
-> Instance.InstanceCalcVesselAeroForces
-> SimulateAeroProperties
-> PrecomputeCenterOfLift
-> CalculateForces
-> DoCalculateForces (several overloaded calls)

This statement checks for aerodynamic failure - getting called on the simulation:

 if (Math.Abs(Vector3d.Dot(scaledForce, forward)) > YmaxForce * failureForceScaling || Vector3d.Exclude(forward, scaledForce).magnitude > XZmaxForce * failureForceScaling)

**Comment by ferram4** [comment]
Yep, makes sense.  This is easily solved by having the CalculateForces method from PrecomputeCenterOfLift pass through double.PositiveInfinity for failureForceScaling.
