### ISSUE TITLE
Updating Spam

### ISSUE THREAD

**Issue by RealKolago** [ferram4/Ferram-Aerospace-Research#71]
FAR floods the log with updating messages in the VAB when I put a part in. 
Testen on vanilla KSP 1.0.2 32 bit and FAR v0.15.1

**Comment by futrtrubl** [comment]
Logs? Screenshots? Modlist?

**Comment by RealKolago** [comment]
Sure: https://www.dropbox.com/s/ou8kks1jp9vtdz4/output_log.zip?dl=0
