### ISSUE TITLE
Updating Spam in Log

### ISSUE THREAD

**Issue by RealKolago** [ferram4/Ferram-Aerospace-Research#73]
FAR floods the log with updating messages in the VAB when I put a part in.
Testen on vanilla KSP 1.0.2 32 bit and FAR v0.15.1

Log: https://www.dropbox.com/s/ou8kks1jp9vtdz4/output_log.zip?dl=0

Sorry, accidentally hit close on the other one.

**Comment by ferram4** [comment]
I need full reproduction steps.  Something specific must cause this, but using any old part doesn't seem to.

**Comment by RealKolago** [comment]
Ok, in the empty VAB place some Pod in the VAB, delete it (drag it back to Partlist) and place some Pod again in the VAB. This triggers the spam every time for me.

**Comment by ferram4** [comment]
I cannot reproduce in the latest dev build.  Grab the dll from the repo and see if that causes the issue.

**Comment by RealKolago** [comment]
The problem stay even with the last DLL from today.

**Comment by ferram4** [comment]
What other mods, and which pod did you use?

**Comment by RealKolago** [comment]
Only ModularFlightIntegrator 1.0 and ModuleManager.2.6.3.dll other than FAR.
System is Windows 7 64bit. Kerbal 1.0.2 32bit.

mk1pod was my last test.

**Comment by ferram4** [comment]
Then I'm sorry, I just can't reproduce the issue.  Try out the latest dev build, I changed a few things that might help.

**Comment by RealKolago** [comment]
Same problem with new dll. Strange that you can't reproduce the issue.

**Comment by RealKolago** [comment]
Arrrg. I messed up my KSP test install directory with some older KSP files. 1000 sorry's!

**Comment by ferram4** [comment]
What ended up being the solution?  A lot of other people have had similar issues, and I'd like to know anything about the source of it.

**Comment by RealKolago** [comment]
I don't know. For vanilla game all is ok now. For my normal game the error still exist. So it is some interaction with one of my 70 mods. I will try to figure it out, but this will require a lot of testing. One of my mods updates the game database and FAR thinks that it has to do something with the new data. So some mod plays ping pong with FAR.

**Comment by RealKolago** [comment]
Another strange thing in my game is that the mouse wheel sensitivity is set from 1 to 0 sometimes and I can't zoom outside of the VAB. But this is another story. :-(

**Comment by ferram4** [comment]
... that doesn't explain anything at all.  FAR doesn't care what the game database is about, all it cares about is if it can grab the mesh from the vehicle and voxelize it.

So this means that we've either got a mod that interferes with mods that create threads outside of Unity to get their work done, or we've got a mod that somehow breaks meshes?

What mods are you running?

**Comment by RealKolago** [comment]
This is a list all my off dll's in GameData:
c:\Kerbal Space Program 1.0\GameData\000_FilterExtensions\FilterExtensions.dll
c:\Kerbal Space Program 1.0\GameData\000_Toolbar\Toolbar.dll
c:\Kerbal Space Program 1.0\GameData\000_USITools\DynamicTanks.dll
c:\Kerbal Space Program 1.0\GameData\000_USITools\USITools.dll
c:\Kerbal Space Program 1.0\GameData\AquilaEnterprises\Bulb\Plugin\Bulb.dll
c:\Kerbal Space Program 1.0\GameData\AutoAsparagus\AutoAsparagus.dll
c:\Kerbal Space Program 1.0\GameData\AutoSmartParts\Plugins\AutoSmartParts.dll
c:\Kerbal Space Program 1.0\GameData\AviationLights\Plugins\AviationLights.dll
c:\Kerbal Space Program 1.0\GameData\B9_Aerospace\Plugins\B9_Aerospace_WingStuff.dll
c:\Kerbal Space Program 1.0\GameData\BahaSP\Parts\critterCrawler\CritterCrawler.dll
c:\Kerbal Space Program 1.0\GameData\BahaSP\Plugins\BDAnimationModules.dll
c:\Kerbal Space Program 1.0\GameData\BetterBuoyancy\Plugins\BetterBuoyancy.dll
c:\Kerbal Space Program 1.0\GameData\BetterTimeWarp\BetterTimeWarp.dll
c:\Kerbal Space Program 1.0\GameData\CapCom\CapCom.dll
c:\Kerbal Space Program 1.0\GameData\Chatterer\Plugins\Chatterer.dll
c:\Kerbal Space Program 1.0\GameData\CollisionFX\Plugins\CollisionFX.dll
c:\Kerbal Space Program 1.0\GameData\DavonTCsystemsMod\Plugins\DifferentialThrust.dll
c:\Kerbal Space Program 1.0\GameData\DeadlyReentry\Plugins\DeadlyReentry.dll
c:\Kerbal Space Program 1.0\GameData\Diazo\ActsEW\ActsEW.dll
c:\Kerbal Space Program 1.0\GameData\Diazo\AGExt\AGExt.dll
c:\Kerbal Space Program 1.0\GameData\Diazo\AGExt\kOSVoidAction.dll
c:\Kerbal Space Program 1.0\GameData\Diazo\AutoAction\AutoAction.dll
c:\Kerbal Space Program 1.0\GameData\Diazo\TWR1\TWR1.dll
c:\Kerbal Space Program 1.0\GameData\DistantObject\DistantObject.dll
c:\Kerbal Space Program 1.0\GameData\EditorExtensions\EditorExtensions.dll
c:\Kerbal Space Program 1.0\GameData\EnhancedNavBall\Plugins\EnhancedNavBall.dll
c:\Kerbal Space Program 1.0\GameData\EVAManager.dll
c:\Kerbal Space Program 1.0\GameData\ExceptionDetector\ExceptionDetector.dll
c:\Kerbal Space Program 1.0\GameData\ExtraplanetaryLaunchpads\Plugins\KSPAPIExtensions.dll
c:\Kerbal Space Program 1.0\GameData\ExtraplanetaryLaunchpads\Plugins\Launchpad.dll
c:\Kerbal Space Program 1.0\GameData\FerramAerospaceResearch\Plugins\FerramAerospaceResearch.dll
c:\Kerbal Space Program 1.0\GameData\FerramAerospaceResearch\Plugins\ferramGraph.dll
c:\Kerbal Space Program 1.0\GameData\FerramAerospaceResearch\Plugins\Scale_Redist.dll
c:\Kerbal Space Program 1.0\GameData\Firespitter\Plugins\Firespitter.dll
c:\Kerbal Space Program 1.0\GameData\FlagRotate\FlagRotate.dll
c:\Kerbal Space Program 1.0\GameData\FTLDrive\Plugins\FTLDrive.dll
c:\Kerbal Space Program 1.0\GameData\Fusebox\Plugins\Fusebox.dll
c:\Kerbal Space Program 1.0\GameData\GForce\Plugins\GForce.dll
c:\Kerbal Space Program 1.0\GameData\GPOSpeedFuelPump\Plugins\GPOSpeedFuelPump.dll
c:\Kerbal Space Program 1.0\GameData\HaystackContinued\HaystackContinued.dll
c:\Kerbal Space Program 1.0\GameData\HeatWarning\HeatWarning.dll
c:\Kerbal Space Program 1.0\GameData\IntakeBuildAid\IntakeBuildAid.dll
c:\Kerbal Space Program 1.0\GameData\InterstellarFuelSwitch\Plugins\InterstellarFuelSwitch.dll
c:\Kerbal Space Program 1.0\GameData\JSI\RasterPropMonitor\Plugins\MechJebRPM.dll
c:\Kerbal Space Program 1.0\GameData\JSI\RasterPropMonitor\Plugins\RasterPropMonitor.dll
c:\Kerbal Space Program 1.0\GameData\JSIPartUtilities.dll
c:\Kerbal Space Program 1.0\GameData\KAS\Plugins\KAS.dll
c:\Kerbal Space Program 1.0\GameData\KerbalEngineer\KerbalEngineer.dll
c:\Kerbal Space Program 1.0\GameData\KerbalFoundries\Plugins\KerbalFoundries.dll
c:\Kerbal Space Program 1.0\GameData\KerbalJointReinforcement\Plugin\KerbalJointReinforcement.dll
c:\Kerbal Space Program 1.0\GameData\Kerbaltek\HyperEdit.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\CraftHistory\CraftHistory.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\KerboKatzUtilities.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\RecoverAll\RecoverAll.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\SmallUtilities\SmallUtilities.Afterburner.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\SmallUtilities\SmallUtilities.DisableTempGagues.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\SmallUtilities\SmallUtilities.EditorCamUtilities.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\SmallUtilities\SmallUtilities.FPSLimiter.dll
c:\Kerbal Space Program 1.0\GameData\KerboKatz\SmallUtilities\SmallUtilities.FPSViewer.dll
c:\Kerbal Space Program 1.0\GameData\KineTechAnimation\Plugins\KineTechAnimation.dll
c:\Kerbal Space Program 1.0\GameData\KIS\Plugins\KIS.dll
c:\Kerbal Space Program 1.0\GameData\Klockheed_Martian_Gimbal\Plugins\km_Gimbal.dll
c:\Kerbal Space Program 1.0\GameData\KSEA\Sentinel\Sentinel.dll
c:\Kerbal Space Program 1.0\GameData\KSP-AVC\KSP-AVC.dll
c:\Kerbal Space Program 1.0\GameData\MagicSmokeIndustries\IRSequencer\Plugins\IRSequencer.dll
c:\Kerbal Space Program 1.0\GameData\MagicSmokeIndustries\Plugins\InfernalRobotics.dll
c:\Kerbal Space Program 1.0\GameData\MagicSmokeIndustries\Plugins\KSPAPIExtensions.dll
c:\Kerbal Space Program 1.0\GameData\MagicSmokeIndustries\Plugins\Scale_Redist.dll
c:\Kerbal Space Program 1.0\GameData\MechJeb2\Plugins\MechJeb2.dll
c:\Kerbal Space Program 1.0\GameData\MenuStabilizer.dll
c:\Kerbal Space Program 1.0\GameData\MinAmbience\MinAmbience.dll
c:\Kerbal Space Program 1.0\GameData\ModularFlightIntegrator\ModularFlightIntegrator.dll
c:\Kerbal Space Program 1.0\GameData\ModularFuelTanks\Plugins\KSPAPIExtensions.dll
c:\Kerbal Space Program 1.0\GameData\ModularFuelTanks\Plugins\modularFuelTanks.dll
c:\Kerbal Space Program 1.0\GameData\ModuleManager.2.6.3.dll
c:\Kerbal Space Program 1.0\GameData\ModuleRCSFX\Plugins\ModuleRCSFX.dll
c:\Kerbal Space Program 1.0\GameData\NavHud\Plugins\NavHud.dll
c:\Kerbal Space Program 1.0\GameData\NearFutureSolar\Plugins\NearFutureSolar.dll
c:\Kerbal Space Program 1.0\GameData\Nereid\FinalFrontier\Plugins\FinalFrontier.dll
c:\Kerbal Space Program 1.0\GameData\Nereid\S.A.V.E\Plugins\S.A.V.E.dll
c:\Kerbal Space Program 1.0\GameData\NRAP\Plugins\NRAP.dll
c:\Kerbal Space Program 1.0\GameData\PartWizard\Plugins\PartWizard.dll
c:\Kerbal Space Program 1.0\GameData\PlaneMode\Plugins\PlaneMode.dll
c:\Kerbal Space Program 1.0\GameData\PlanetShine\Plugins\PlanetShine.dll
c:\Kerbal Space Program 1.0\GameData\ProceduralFairings\KSPAPIExtensions.dll
c:\Kerbal Space Program 1.0\GameData\ProceduralFairings\ProceduralFairings.dll
c:\Kerbal Space Program 1.0\GameData\ProceduralParts\Plugins\KSPAPIExtensions.dll
c:\Kerbal Space Program 1.0\GameData\ProceduralParts\Plugins\ProceduralParts.dll
c:\Kerbal Space Program 1.0\GameData\QuantumStrutsContinued\Plugins\QuantumStrutsContinued.dll
c:\Kerbal Space Program 1.0\GameData\QuickGoTo\Plugins\QuickGoTo.dll
c:\Kerbal Space Program 1.0\GameData\QuickHide\Plugins\QuickHide.dll
c:\Kerbal Space Program 1.0\GameData\QuickScroll\Plugins\QuickScroll.dll
c:\Kerbal Space Program 1.0\GameData\QuickSearch\Plugins\QuickSearch.dll
c:\Kerbal Space Program 1.0\GameData\QuickStart\Plugins\QuickStart.dll
c:\Kerbal Space Program 1.0\GameData\RCSBuildAid\Plugins\RCSBuildAid.dll
c:\Kerbal Space Program 1.0\GameData\RCSBuildAid\Plugins\RCSBuildAidToolbar.dll
c:\Kerbal Space Program 1.0\GameData\RealChute\Plugins\RealChute.dll
c:\Kerbal Space Program 1.0\GameData\REPOSoftTech\AmpYear\Plugins\AmpYear.dll
c:\Kerbal Space Program 1.0\GameData\REPOSoftTech\AmpYear\Plugins\AYInterfaces.dll
c:\Kerbal Space Program 1.0\GameData\REPOSoftTech\KabinKraziness\Plugins\KKInterfaces.dll
c:\Kerbal Space Program 1.0\GameData\RoutineMissionManager\CommercialOfferings.dll
c:\Kerbal Space Program 1.0\GameData\SCANsat\Plugins\SCANmechjeb.dll
c:\Kerbal Space Program 1.0\GameData\SCANsat\Plugins\SCANsat.dll
c:\Kerbal Space Program 1.0\GameData\ScienceAlert\ScienceAlert.dll
c:\Kerbal Space Program 1.0\GameData\ShipManifest\Plugins\CLSInterfaces.dll
c:\Kerbal Space Program 1.0\GameData\ShipManifest\Plugins\ShipManifest.dll
c:\Kerbal Space Program 1.0\GameData\SimpleOrbitCalculator\Plugins\SimpleOrbitCalculator.dll
c:\Kerbal Space Program 1.0\GameData\SmartParts\Plugins\KSPAPIExtensions.dll
c:\Kerbal Space Program 1.0\GameData\SmartParts\Plugins\SmartParts.dll
c:\Kerbal Space Program 1.0\GameData\SmartStage\Plugins\SmartStage.dll
c:\Kerbal Space Program 1.0\GameData\SmokeScreen\SmokeScreen.dll
c:\Kerbal Space Program 1.0\GameData\StageRecovery\StageRecovery.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\BandwidthFix\BandwidthFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\KerbalDebrisFix\KerbalDebrisFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\ModuleAeroSurfaceFix\ModuleAeroSurfaceFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\ModuleControlSurfaceFix\ModuleControlSurfaceFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\ModuleGimbalFix\ModuleGimbalFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\ModuleParachuteFix\ModuleParachuteFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\ModuleProceduralFairingFix\ModuleProceduralFairingFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\ModuleWheelFix\ModuleWheelFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\PhysicsFix\PhysicsFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\StickyLaunchPadFix\StickyLaunchPadFix.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\StockPlusController.dll
c:\Kerbal Space Program 1.0\GameData\StockBugFixModules\SymmetryActionFix\SymmetryActionFix.dll
c:\Kerbal Space Program 1.0\GameData\TacFuelBalancer\TacFuelBalancer.dll
c:\Kerbal Space Program 1.0\GameData\TakeCommand\TakeCommand.dll
c:\Kerbal Space Program 1.0\GameData\TextureReplacer\Plugins\TextureReplacer.dll
c:\Kerbal Space Program 1.0\GameData\Thermometer\Plugins\Thermometer.dll
c:\Kerbal Space Program 1.0\GameData\ThrottleControlledAvionics\Plugins\ThrottleControlledAvionics.dll
c:\Kerbal Space Program 1.0\GameData\TimeControl\TimeControl.dll
c:\Kerbal Space Program 1.0\GameData\ToadicusTools\ToadicusTools.dll
c:\Kerbal Space Program 1.0\GameData\TriggerTech\KerbalAlarmClock\KerbalAlarmClock.dll
c:\Kerbal Space Program 1.0\GameData\TriggerTech\KSPAlternateResourcePanel\KSPAlternateResourcePanel.dll
c:\Kerbal Space Program 1.0\GameData\TriggerTech\TransferWindowPlanner\TransferWindowPlanner.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableAnimateGeneric.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableCrossFeed.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableDecouplers.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableDockingNode.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableEngineFairings.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableEVA.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableFuelPumps.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableGimbals.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableIntakes.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableLadders.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableParachutes.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableRCS.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableReactionWheels.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableSAS.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableSolarPanels.dll
c:\Kerbal Space Program 1.0\GameData\TweakableEverything\TweakableStaging.dll
c:\Kerbal Space Program 1.0\GameData\TweakScale\plugins\KSPAPIExtensions.dll
c:\Kerbal Space Program 1.0\GameData\TweakScale\plugins\Scale.dll
c:\Kerbal Space Program 1.0\GameData\TweakScale\plugins\Scale_Editor.dll
c:\Kerbal Space Program 1.0\GameData\TweakScale\plugins\Scale_Redist.dll
c:\Kerbal Space Program 1.0\GameData\UmbraSpaceIndustries\Karbonite\Karbonite.dll
c:\Kerbal Space Program 1.0\GameData\UmbraSpaceIndustries\KarbonitePlus\KarbPlus.dll
c:\Kerbal Space Program 1.0\GameData\UmbraSpaceIndustries\Kolonization\KolonyTools.dll
c:\Kerbal Space Program 1.0\GameData\UmbraSpaceIndustries\SrvPack\AirbagTools.dll
c:\Kerbal Space Program 1.0\GameData\UmbraSpaceIndustries\SrvPack\Lifeboat.dll
c:\Kerbal Space Program 1.0\GameData\UmbraSpaceIndustries\WarpDrive\WarpEngine.dll
c:\Kerbal Space Program 1.0\GameData\UniversalStorage\Plugins\AdvancedAnimator.dll
c:\Kerbal Space Program 1.0\GameData\WaypointManager\WaypointManager.dll
c:\Kerbal Space Program 1.0\GameData\WildBlueIndustries\Cooldown.dll
c:\Kerbal Space Program 1.0\GameData\WildBlueIndustries\DSEV\SpinHub.dll
c:\Kerbal Space Program 1.0\GameData\WildBlueIndustries\DSEVUtils.dll
c:\Kerbal Space Program 1.0\GameData\WildBlueIndustries\WildBlueTools.dll

**Comment by RealKolago** [comment]
First I will try all the procedural stuff.
B9_Aerospace\Plugins\B9_Aerospace_WingStuff.dll
ProceduralFairings\ProceduralFairings.dll
ProceduralParts\Plugins\ProceduralParts.dll

**Comment by RealKolago** [comment]
Ok, Kerbal with FAR and

B9_Aerospace\Plugins\B9_Aerospace_WingStuff.dll
ProceduralFairings\ProceduralFairings.dll
ProceduralParts\Plugins\ProceduralParts.dll
TweakScale

is ok.

**Comment by RealKolago** [comment]
adding TweakableEverything -> OK
adding DeadlyReentry -> OK
adding Adjustable Landing Gear -> OK

**Comment by RealKolago** [comment]
adding StockBugFixModules -> OK
adding FlagRotate -> OK
adding all KerboKatz -> OK

**Comment by RealKolago** [comment]
MagicSmokeIndustries\Plugins -> OK
Firespitter\Plugins\Firespitter.dll only -> OK
all Diazo -> OK
NRAP\Plugins\NRAP.dll -> OK

**Comment by RealKolago** [comment]
QuickGoTo\Plugins\QuickGoTo.dll
QuickHide\Plugins\QuickHide.dll
QuickScroll\Plugins\QuickScroll.dll
QuickSearch\Plugins\QuickSearch.dll
QuickStart\Plugins\QuickStart.dll

and we have the error!

**Comment by RealKolago** [comment]
QuickStart\Plugins\QuickStart.dll  -> OK
QuickSearch\Plugins\QuickSearch.dll  -> OK
QuickScroll\Plugins\QuickScroll.dll -> OK
QuickRevert.dll -> Ok
QuickGoTo\Plugins\QuickGoTo.dll -> OK
QuickHide\Plugins\QuickHide.dll -> error!

**Comment by RealKolago** [comment]
So we have the villain... QuickHide!

Testet with vanilla KSP and only

  FerramAerospaceResearch
  ModularFlightIntegrator
  QuickHide

installed.

**Comment by RealKolago** [comment]
https://github.com/malahx/QuickHide

**Comment by RealKolago** [comment]
KSP and only QuickHide is OK.

**Comment by RealKolago** [comment]
Log with the error: https://www.dropbox.com/s/n5gjtti49m6qdvg/output_log3.zip?dl=0

**Comment by RealKolago** [comment]
https://github.com/malahx/QuickHide/issues/3
