### ISSUE TITLE
Aerodynamics break after a while. 

### ISSUE THREAD

**Issue by thomas15v** [ferram4/Ferram-Aerospace-Research#74]
When you like keep testing planes. After a while its behaviour totally changes from flying to exploding :worried:. When I was looking what was wrong with my plane using the simulator. This error occured: http://hastebin.com/usorodeciq.avrasm

KSP info: Kerbal Space Program - 1.0.2.0 (LinuxPlayer) Steam
OS: Linux 3.19 Ubuntu 15.04 64bit
CPU: Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8)
RAM: 23878
GPU: GeForce GTX 770/PCIe/SSE2 (2048MB)
SM: 30 (OpenGL 4.5 [4.5.0 NVIDIA 346.59])
RT Formats: ARGB32, Depth, ARGBHalf, RGB565, ARGB4444, ARGB1555, Default, DefaultHDR, ARGBFloat, RGFloat, RGHalf, RFloat, RHalf, R8

**Comment by ferram4** [comment]
I need reproduction steps and a full copy of the log.  I've gotten a lot of reports like this, but none of them of have solid reproduction steps.

**Comment by thomas15v** [comment]
Using [ExceptionDetector](https://github.com/godarklight/ExceptionDetector) I noticed FAR throws errors on the following things:
- Kerbals going EVA and touching things.
- *Wings crashing in to the surface*.

It happened again in this [log](https://drive.google.com/file/d/0B4cT1XPmcnpKYTdjTDc2d2N1eDA/view?pli=1). And I did the following:
1. I was flying a plane everything was fine.
2. Tried to land it. But yeah it was dark. So I crashed it :worried:.
3. After the plane crash. I reverted to SPH. And launched a rocket.
4. Rocket lifted up good (A bit to good :worried:)
5. When returning to the surface. I slammed in to the ground at 2100m/s. Parachutes didn't do anything.

**Comment by ferram4** [comment]
Once again, I need a full copy of the log.  Further, your reproduction steps do not cause the issue for me in the latest dev build, and the exceptions that do exist are irrelevant to this issue (though they will be fixed).  Grab the dll from the repo and attempt to reproduce it with the latest build.

**Comment by space-is-hard** [comment]
Full copy of log: https://www.dropbox.com/s/y93ofzrxqaa7n2c/FAR-Break-KSP.log?dl=0

Bonus GFY: http://gfycat.com/VigorousKnobbyJoey (sorry about my retarded gif recorder)

It appears to happen after roughly an hour and a half of continuous play. I don't have time right now to try it again on a clean install. I'll attempt it tomorrow.

**Comment by ferram4** [comment]
Try the latest build in the repo.  It seems to have fixed the issue.

**Comment by space-is-hard** [comment]
Unable to reproduce with 15.2. Thanks!

**Comment by thomas15v** [comment]
Same here :smile:. I haven't noticed this issue anymore.
