### ISSUE TITLE
Parachutes deploying too early

### ISSUE THREAD

**Issue by oobayly** [ferram4/Ferram-Aerospace-Research#77]
A bug was corrected in RealChute where the parachutes were being deployed too early - for example at 0.5kPa (26,500m) instead of .5atm (500kPa - 3,500m). It's still present in the version on Kerbal Stuff, but I don't know if it's been fixed on master - I'm going to have a look now, and see if I can create a pull request.

See RealChute commit StupidChris/RealChute@a8b06539c6c261ba338359b00d9cd6a75de33776

**Comment by ferram4** [comment]
Well, it is now.  Thanks.
