### ISSUE TITLE
Wishlist: do not revoxelise in vacuum

### ISSUE THREAD

**Issue by damerell** [ferram4/Ferram-Aerospace-Research#86]
It struck me, as part of the discussion on another issue, that constantly animated modules like rotating habitat sections will cause constant vessel voxelisation. Would it not be possible to suppress this in vacuum altogether?

**Comment by ferram4** [comment]
No.  Voxelization in vacuum is required to work with the stock game's "occluded" settings for enclosed RCS thrusters, engines, etc.  Not voxelizing would result in similar behavior as #67 and there isn't anything I can do to fix this.

Only option is to ignore certain animations, but even then, I can't decide which animations to ignore and which to consider.  Under those circumstances, I have to take the most conservative options, which is voxelize everything.

**Comment by damerell** [comment]
I understand. Sorry for the pointless issue.

**Comment by ferram4** [comment]
No problem, it's understandable.  It's also not pointless, because now I can point to this if/when this request comes up again. :)
