### ISSUE TITLE
drag gets weird with occupied command seat in a mk2 cargo bay

### ISSUE THREAD

**Issue by rtetelman** [ferram4/Ferram-Aerospace-Research#97]
with the command seat unoccupied, drag is normal. with a kerbal in it far's flight data claims a drag on the order of -30 mN (and observed much higher drag than when the seat is empty)
![220200_screenshots_2015-07-01_00001](https://cloud.githubusercontent.com/assets/1085558/8488437/5a14cf0c-20c7-11e5-838c-dfc885b39968.jpg)
craft used to reproduce the issue: https://gist.github.com/rtetelman/bdfa5a26bbd33fdd88ed

**Comment by ferram4** [comment]
This appears to have been fixed in the current dev build.
